import { expect, test } from "@playwright/test";

test("creates and persists an ordered text section", async ({ page }) => {
    await page.goto("/");
    await expect(page.getByText("Build your document in sections")).toBeVisible();
    await page.getByRole("button", { name: "Add section" }).click();
    await page.getByRole("button", { name: /Text Paragraphs/ }).click();
    await page.getByPlaceholder("Optional heading").fill("Project overview");
    await page.getByPlaceholder("Write an explanation, notes, or Markdown...").fill("This is the **first** section.");
    await expect(page.locator("#preview-document").getByText("Project overview")).toBeVisible();
    await page.waitForTimeout(1000);
    await page.reload();
    await expect(page.getByPlaceholder("Optional heading")).toHaveValue("Project overview");
});

test("adds code, output, and chart section types", async ({ page }) => {
    await page.goto("/");
    for (const name of ["Code", "Output", "Chart"]) {
        await page.getByRole("button", { name: "Add section", exact: true }).click();
        await page.getByRole("button", { name: new RegExp(`^${name}`) }).click();
    }
    await expect(page.getByText("3 sections")).toBeVisible();
    await expect(page.getByLabel("Chart type")).toBeVisible();
});

test("generates a downloadable PDF", async ({ page }) => {
    await page.goto("/");
    await page.getByRole("button", { name: "Add section" }).click();
    await page.getByRole("button", { name: /Text Paragraphs/ }).click();
    await page.getByPlaceholder("Optional heading").fill("Download check");
    await page.getByPlaceholder("Write an explanation, notes, or Markdown...").fill("A short document generated by FolioForge.");
    const downloadPromise = page.waitForEvent("download", { timeout: 30000 });
    await page.getByRole("button", { name: "Generate PDF" }).click();
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toMatch(/\.pdf$/);
});

test("pastes a clipboard image into a new image section", async ({ page }) => {
    await page.goto("/");
    await page.evaluate(() => {
        const base64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
        const bytes = Uint8Array.from(atob(base64), (character) => character.charCodeAt(0));
        const transfer = new DataTransfer();
        transfer.items.add(new File([bytes], "clipboard.png", { type: "image/png" }));
        const pasteEvent = new Event("paste", { bubbles: true, cancelable: true });
        Object.defineProperty(pasteEvent, "clipboardData", { value: transfer });
        window.dispatchEvent(pasteEvent);
    });
    await expect(page.getByText("Image", { exact: true })).toBeVisible();
    await expect(page.getByText("Replace clipboard.png")).toBeVisible();
    await expect(page.getByText("Image pasted as a new section.")).toBeVisible();
});

test("inserts a selected section directly below an existing section", async ({ page }) => {
    await page.goto("/");
    await page.getByRole("button", { name: "Add section" }).click();
    await page.getByRole("button", { name: /Text Paragraphs/ }).click();
    await page.getByPlaceholder("Optional heading").fill("First");

    const firstCard = page.locator("[data-section-id]").first();
    await firstCard.getByRole("button", { name: "Add section below" }).click();
    await firstCard.getByRole("button", { name: /^Code/ }).click();

    await expect(page.getByText("2 sections", { exact: true })).toBeVisible();
    const cards = page.locator("[data-section-id]");
    await expect(cards.nth(0).getByText("Text", { exact: true })).toBeVisible();
    await expect(cards.nth(1).getByText("Code", { exact: true })).toBeVisible();
});

test("places adjacent image sections side by side in landscape", async ({ page }) => {
    await page.goto("/");
    await page.getByRole("button", { name: "Landscape" }).click();
    for (let index = 0; index < 2; index += 1) {
        await page.getByRole("button", { name: "Add section", exact: true }).click();
        await page.getByRole("button", { name: /^Image/ }).click();
    }
    await expect(page.locator("#preview-document [data-image-row]")).toHaveCount(1);
});

test("exports an editable Word document", async ({ page }) => {
    await page.goto("/");
    await page.getByRole("button", { name: "Add section", exact: true }).click();
    await page.getByRole("button", { name: /Text Paragraphs/ }).click();
    await page.getByPlaceholder("Optional heading").fill("Editable section");
    await page.getByPlaceholder("Write an explanation, notes, or Markdown...").fill("This text should remain editable in Word.");
    const downloadPromise = page.waitForEvent("download", { timeout: 30000 });
    await page.getByRole("button", { name: "Export editable Word document" }).click();
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toMatch(/\.docx$/);
});
